# FreeSO Settings File. Properties are self explanatory.
UseDirectx=false
ShowHints=true
CurrentLang=0
LoginServerPort=2106
ClientVersion=0
DebugEnabled=false
ScaleUI=false
CityShadows=false
ShadowQuality=2048
SimulationShadows=true
AntiAlias=false
EdgeScroll=true
Lighting=true
FXVolume=10
MusicVolume=10
VoxVolume=10
AmbienceVolume=1
StartupPath=
DocumentsPath=
LoginServerIP=127.0.0.1
Windowed=true
GraphicsWidth=1366
GraphicsHeight=705
LastUser=
SkipIntro=true
LastHead=0
LastBody=0
LastGender=true
LastSkin=0
Language=1
